--- 
clone: 
  depth: 1
kind: pipeline
name: WHYRED
steps: 
  - 
    commands:
      - "curl https://raw.githubusercontent.com/Reinazhard/myscripts/master/kernel.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: azrim89/kernel:latest
    name: Zhard-Lair

--- 
clone: 
  depth: 1
kind: pipeline
name: TULIP
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/Reinazhard/myscripts/tulip/kernel.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: azrim89/kernel:latest
    name: Zhard-Lair

--- 
clone: 
  depth: 1
kind: pipeline
name: LAVENDER
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/Reinazhard/myscripts/lavender/kernel.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: azrim89/kernel:latest
    name: Zhard-Lair

--- 
clone: 
  depth: 1
kind: pipeline
name: WAYNE
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/Reinazhard/myscripts/wayne/kernel.sh | bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: azrim89/kernel:latest
    name: Zhard-Lair
